[pytest]
addopts = -v
markers =
    integration: mark test as an integration test
testpaths = tests/unit
filterwarnings =
    # Suppress upstream DeprecationWarning from httplib2 (via google-api-python-client)
    # This is present in the latest SDKs as of Dec 26, 2025.
    ignore::DeprecationWarning:httplib2.auth
